version: '2.1'

volumes:
  pimcore-db:
    driver: local

services:
  pimcore:
    image: trydirect/pimcore:6
    build: ./build
    container_name: pimcore
    hostname: pimcore
    user: root
    restart: always
    ports:
      - "443:443"
      - "80:8080"
    volumes:
      - ./build/configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/configs/nginx/conf.d:/etc/nginx/conf.d
      - ./build/configs/certs/letsencrypt:/etc/letsencrypt
      - ./build/configs/certs/ssl:/etc/nginx/ssl
      - ./build/configs/cron:/var/spool/cron/crontabs
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: pimcoredb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    volumes:
      - pimcore-db:/var/lib/mysql
      - ./build/scripts:/scripts
    env_file:
      - .env
